# =============================================
# Perfil de produccion: PostgreSQL (Render)
# Las variables de entorno las provee Render
# =============================================
spring.application.name=layers

# Render inyecta DATABASE_URL automaticamente
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate - PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Puerto que Render asigna
server.port=${PORT:8080}
